### ISSUE TITLE
off don't work

### ISSUE THREAD

**Issue by toshibochan** [jamesblanksby/homebridge-gpio#3]
just install the plugin, ON is working ok but OFF not working.

**Comment by toshibochan** [comment]
and when press ON come back= 
"Turning on pin #7
Error when try to open pin7
gpio-admin: could mot flush data to /sys/class/gpio/export: Device or rescue busy"

Same for OFF=
"Turning off pin #7
Error when try to open pin7
gpio-admin: could mot flush data to /sys/class/gpio/export: Device or rescue busy"

**Comment by 128keaton** [comment]
Same here man

**Comment by tktino** [comment]
Same here, @jamesblanksby what's going on?

Seems like the first time i flip the switch, doesn't turn on. Though it will turn on what I turn it off and turn off when I turn it on.

**Comment by 128keaton** [comment]
I ended up writing something custom, I think that this plugin is not worth using.

**Comment by tinobedi** [comment]
what is your custom solution?

**Comment by toshibochan** [comment]
Please post you custom index

**Comment by 128keaton** [comment]
@tinobedi @toshibochan sure, its a bit really custom

https://github.com/128keaton/relay-gpio-keaton

https://github.com/128keaton/homebridge-gpio-piholder

**Comment by tinobedi** [comment]
thanks for sharing, how would we write that into the config file for homebridge? examples :)

**Comment by jamesblanksby** [comment]
Unfortunately, I have no time to spend on debugging and fixing this issue, everything is working great for me and this repo was designed primarily as a personal project that I thought other developers might find useful. Obviously, if you want to give back to the open source community merge requests are welcome. I am closing this thread because it is off topic now.

**Comment by tktino** [comment]
@128keaton when you do get a chance, please post an example your github page. thanks :).

Also thanks @jamesblanksby

**Comment by 128keaton** [comment]
@tktino ok, its not hard to figure out. I posted the repo as a favor to you guys, since I got something working

**Comment by tinobedi** [comment]
Thank you, I'll move the conversation to your repo to respect this repos author. :)
